env:
  browser: true
  es6: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  {
    "indent": ["error", 4],
    "import/no-extraneous-dependencies": 0,
    "import/prefer-default-export": 0,
    "arrow-parens": 0,
  }
